# Rubocop,  we're buddies and all,  but we're going to have to disagree on the following -
AllCops:
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'

LineLength:
  Max: 180

SingleSpaceBeforeFirstArg:
  Enabled: false

UnusedBlockArgument:
  Enabled: false

WordArray:
  MinSize: 5
